### ISSUE TITLE
编译报错了。不知道是缺少了什么。可以帮忙看下吗

### ISSUE THREAD

**Issue by aiden66535** [KnightAndroid/wanandroid#2]
![image](https://github.com/KnightAndroid/wanandroid/assets/16305029/2764de81-1400-41d4-a439-9d7d9a7ef834)

**Comment by aiden66535** [comment]
已解决，我暂时先把混淆相关的注释掉了

**Comment by KnightAndroid** [comment]
> 已解决，我暂时先把混淆相关的注释掉了

混淆问题么，我这边没问题
